import React, { useEffect } from 'react';
import Head from 'next/head'
import Link from 'next/link';
import styles from '../../styles/analog.module.sass'
import { ArrowLeft } from 'react-feather'

const Analog: React.FC = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://unpkg.com/feather-icons"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.content}>
        <div className={styles.container}>
          <Link href="/"><div className={styles.button}><ArrowLeft /></div></Link>
          <div className={styles.box}>
            <div className={styles.clock}>
              <div className={styles.hour}>
                <div className={styles.hr} id="hr"></div>
              </div>
              <div className={styles.min}>
                <div className={styles.mn} id="mn"></div>
              </div>
              <div className={styles.sec}>
                <div className={styles.sc} id="sc"></div>
              </div>
            </div>      
          </div>
        </div>
      </main>
    </>
  );
};

export default Analog;
